# Development: DB only. Run API (and frontend) from host. Use: docker compose -f compose.dev.yml up -d
services:
  dev-db:
    image: postgres:15
    container_name: dockiup-postgres-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: dockiupdb-dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
