export * from './activity.service';
import { ActivityService } from './activity.service';
export * from './app.service';
import { AppService } from './app.service';
export * from './container.service';
import { ContainerService } from './container.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './nodes.service';
import { NodesService } from './nodes.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './webhook.service';
import { WebhookService } from './webhook.service';
export const APIS = [ActivityService, AppService, ContainerService, DashboardService, NodesService, ProjectService, WebhookService];
