// <auto-generated />
using System;
using DockiUp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DockiUp.Infrastructure.Migrations
{
    [DbContext(typeof(DockiUpDbContext))]
    [Migration("20260223093907_AddLastPeriodicUpdateAt")]
    partial class AddLastPeriodicUpdateAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DockiUp.Domain.ProjectInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ComposePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DockerProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastPeriodicUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PeriodicIntervalInMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectOrigin")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectUpdateMethod")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
