/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ContainerOriginType = 'Unknown' | 'Git' | 'Compose' | 'Local';

export const ContainerOriginType = {

    Unknown: 'Unknown' as ContainerOriginType,

    Git: 'Git' as ContainerOriginType,

    Compose: 'Compose' as ContainerOriginType,

    Local: 'Local' as ContainerOriginType
};

