/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ContainerUpdateMethod = 0 | 1 | 2 | 3;

export const ContainerUpdateMethod = {

    NUMBER_0: 0 as ContainerUpdateMethod,

    NUMBER_1: 1 as ContainerUpdateMethod,

    NUMBER_2: 2 as ContainerUpdateMethod,

    NUMBER_3: 3 as ContainerUpdateMethod
};

