/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ContainerUpdateMethod = 'unknown' | 'Webhook' | 'Manual' | 'Periodically';

export const ContainerUpdateMethod = {

    Unknown: 'unknown' as ContainerUpdateMethod,

    Webhook: 'Webhook' as ContainerUpdateMethod,

    Manual: 'Manual' as ContainerUpdateMethod,

    Periodically: 'Periodically' as ContainerUpdateMethod
};

