/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ContainerOriginType = 0 | 1 | 2 | 3;

export const ContainerOriginType = {

    NUMBER_0: 0 as ContainerOriginType,

    NUMBER_1: 1 as ContainerOriginType,

    NUMBER_2: 2 as ContainerOriginType,

    NUMBER_3: 3 as ContainerOriginType
};

