/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContainerDto { 
    id: string;
    name: string;
    status: string;
    state: number;
    serviceName: string;
    projectName: string;
}

