/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateMethodType } from './updateMethodType';


export interface ContainerDto { 
    id: string | null;
    name: string | null;
    status: string | null;
    state: UpdateMethodType;
    serviceName: string | null;
    projectName: string | null;
}
export namespace ContainerDto {
}


