/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityEntryDto } from './activityEntryDto';
import { DashboardStatsDtoTotalProjects } from './dashboardStatsDtoTotalProjects';


export interface DashboardStatsDto { 
    totalProjects: DashboardStatsDtoTotalProjects;
    totalContainers: DashboardStatsDtoTotalProjects;
    runningContainers: DashboardStatsDtoTotalProjects;
    recentActivity: Array<ActivityEntryDto>;
}

