/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContainerDto } from './containerDto';


export interface ProjectDto { 
    name: string | null;
    containers: Array<ContainerDto> | null;
}

