/**
 * DockiUp.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProblemDetailsStatus } from './problemDetailsStatus';
import { ContainerDto } from './containerDto';


export interface ProjectDto { 
    id?: ProblemDetailsStatus | null;
    projectName: string;
    dockerProjectName: string;
    projectDescription: string;
    managedByDockiUp: boolean;
    containers: Array<ContainerDto>;
    projectPath?: string | null;
    updateMethod?: string | null;
}

