/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectOriginType } from './projectOriginType';
import { ProjectUpdateMethod } from './projectUpdateMethod';


export interface SetupProjectDto { 
    projectName: string | null;
    description?: string | null;
    projectOrigin: ProjectOriginType;
    gitUrl?: string | null;
    compose?: string | null;
    path?: string | null;
    projectUpdateMethod: ProjectUpdateMethod;
    webhookUrl?: string | null;
    periodicIntervalInMinutes?: number | null;
}
export namespace SetupProjectDto {
}


