/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContainerOriginType } from './containerOriginType';
import { ContainerUpdateMethod } from './containerUpdateMethod';


export interface SetupProjectDto { 
    projectName: string | null;
    containerOrigin: ContainerOriginType;
    updateMethod: ContainerUpdateMethod;
    compose?: string | null;
    gitUrl?: string | null;
    path?: string | null;
}
export namespace SetupProjectDto {
}


