/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UpdateMethodType = 0 | 1 | 2 | 3 | 4 | 5;

export const UpdateMethodType = {

    NUMBER_0: 0 as UpdateMethodType,

    NUMBER_1: 1 as UpdateMethodType,

    NUMBER_2: 2 as UpdateMethodType,

    NUMBER_3: 3 as UpdateMethodType,

    NUMBER_4: 4 as UpdateMethodType,

    NUMBER_5: 5 as UpdateMethodType
};

