/**
 * DockiUp.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UpdateMethodType = 'Unknown' | 'Created' | 'Stopped' | 'Running' | 'Updating' | 'Crashed';

export const UpdateMethodType = {

    Unknown: 'Unknown' as UpdateMethodType,

    Created: 'Created' as UpdateMethodType,

    Stopped: 'Stopped' as UpdateMethodType,

    Running: 'Running' as UpdateMethodType,

    Updating: 'Updating' as UpdateMethodType,

    Crashed: 'Crashed' as UpdateMethodType
};

